### ISSUE TITLE
当表单没有任何输入 ，直接点击按钮时，并没有触发验证规则，请问这种情况该怎么处理呢？

### ISSUE THREAD

**Issue by zeronyist** [aweiu/element-ui-verify#12]
非常感谢您所开源的这个易用、优美的验证插件。
但有个问题，我不知道怎么处理，当表单没有任何输入 ，直接点击按钮时，并没有触发验证规则，
请问这种情况该怎么处理呢？

**Comment by aweiu** [comment]
那个输入项你想校验什么？不能为空吗

**Comment by zeronyist** [comment]
是的

**Comment by zeronyist** [comment]
<template>
<el-form :model="model" ref="ruleForm">
  <el-form-item prop="age" verify>
    <el-input v-model="model.age"></el-input>
  </el-form-item>
  <el-form-item>
    <el-button @click="doSave()">保存</el-button>
  </el-form-item>
</el-form>
</template>
<script>
export default {
  data() {
    return {
      model: {
        age: null
      }
    }
  },
  methods: {
    doSave(tab, event) { 
      let self = this;
      self.$refs['ruleForm'].validate((valid) => {
        alert(valid);
      });
    },
  }
}
</script>
比如上面代码，当我点击”保存“按钮时，并没有解发必输校验。

**Comment by zeronyist** [comment]
<template>
<el-form :model="model" ref="ruleForm">
  <el-form-item prop="age" verify>
    <el-input v-model="model.age"></el-input>
  </el-form-item>
  <el-form-item>
    <el-button @click="doSave()">保存</el-button>
  </el-form-item>
</el-form>
</template>
<script>
export default {
  data() {
    return {
      model: {
        age: null
      }
    }
  },
  methods: {
    doSave(tab, event) { 
      let self = this;
      self.$refs['ruleForm'].validate((valid) => {
        alert(valid);
      });
    },
  }
}
</script>
样例代码，点击”保存“按钮时并没有解发必输验证。

**Comment by zeronyist** [comment]
<template>
<el-form :model="model" ref="ruleForm">
  <el-form-item prop="age" verify>
    <el-input v-model="model.age"></el-input>
  </el-form-item>
  <el-form-item>
    <el-button @click="doSave()">保存</el-button>
  </el-form-item>
</el-form>
</template>
<script>
export default {
  data() {
    return {
      model: {
        age: null
      }
    }
  },
  methods: {
    doSave(tab, event) { 
      let self = this;
      self.$refs['ruleForm'].validate((valid) => {
        alert(valid);
      });
    },
  }
}
</script>

**Comment by zeronyist** [comment]
如样例代码，点击”保存“按钮，并没触发必输校验

**Comment by zeronyist** [comment]
[index.zip](https://github.com/aweiu/element-ui-verify/files/2047163/index.zip)

**Comment by aweiu** [comment]
我用的手机。看不了你的代码，建议你再重新看下文档，文档的第一个例子就是不为空检验。

**Comment by zeronyist** [comment]
嗯，您方便时看一下代码，此代码示例当"FieldChange"是可以触发必输校验的。便如果我不做任何输入，直接点击”保存“按钮，无法触发必输校验。

**Comment by aweiu** [comment]
看了下代码，你这个问题其实主要是表单数据默认值导致的，可以参考下本插件的[空检测源码](https://github.com/aweiu/element-ui-verify/blob/master/src/component.ts#L49)

仅针对表单数据来说，对于其`value`值个人理解应当只涉及到三种基本类型，String，Number，Undefined(这里结合Vue来看应是未显式在data中声明的字段值)

因此，对于空输入框来说，无论其值的实际类型是String还是Number，一般的做法都是把绑定值的默认值设为`''`，而不是`null`

**Comment by zeronyist** [comment]
谢谢您的回复，我试试，
建议您能加入null判断，毕竟软件一定要给服务器端做交互。
服务器端的返回值一般不会选择Undefined,
String类型服务器端一般会选择"null"做为返回值。

**Comment by zeronyist** [comment]
对于Number类型，或者为null,或者有值，不会存在''这种情况的。

**Comment by aweiu** [comment]
@zeronyist 确实，结合你描述的该种需求以及`v-model`本身特性和市面上大多数校验插件的做法，已将`null`加入空值的判断。请更新至v1.1.5

**Comment by zeronyist** [comment]
@aweiu ,谢谢。
