### ISSUE TITLE
可以直接调用某个方法  让输入框报错标红并且显示自己的文案么

### ISSUE THREAD

**Issue by leefreeF** [aweiu/element-ui-verify#13]

**Comment by aweiu** [comment]
可以。最简单的方式是通过[ref](https://cn.vuejs.org/v2/api/#ref)获取该form-item的组件实例，然后调用该实例的[validate](https://github.com/ElemeFE/element/blob/dev/packages/form/src/form-item.vue#L172:7)方法

不过不知道你为何要这么做，是要异步校验吗？如果是的话可以直接使用[自定义校验方法](https://github.com/aweiu/element-ui-verify#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%A1%E9%AA%8C%E6%96%B9%E6%B3%95)来实现

**Comment by leefreeF** [comment]
谢谢

**Comment by leefreeF** [comment]
我这边是提交一个表单   在第一次提交的时候  正常的校验，  错误标红提示 ，然后提交表单 ，审核人员可以退回 ， 数据回显  要告诉用户哪一条错了  ， 我的意思是通过方法直接让form-item  new Error('自定义文案')   这种需求可以做到么

**Comment by aweiu** [comment]
可以。上面我是就你之前的问题做的回复，单独触发某个表单项的校验。

再说你这个需求，显然还得设计一下表单项的[自定义校验方法](https://github.com/aweiu/element-ui-verify#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%A1%E9%AA%8C%E6%96%B9%E6%B3%95)。
假设后端返回的审核数据是:
```
{
  name: {
    value: '张三',
    valid: false,
    reason: '审核没通过'
  }
}
```
你的自定义校验方法里应当包含上述数据的判断，当前值不能再等于审核未通过的值，如果等于了就callback(Error(`reason`))

这样你就只需要在获取完审核数据后，直接调用`el-form`的[validate](http://element.eleme.io/#/zh-CN/component/form#form-methods)方法即可
