### ISSUE TITLE
[Vue warn]: $attrs is readonly. 與 [Vue warn]: $listeners is readonly.

### ISSUE THREAD

**Issue by iambochen** [aweiu/element-ui-verify#14]
請問什麼情況下會產生這種警告訊息？

**Comment by aweiu** [comment]
这个问题是你修改了vue的只读属性，和本插件无关

**Comment by iambochen** [comment]
不好意思，我不太理解。在哪邊可以設定你說的 vue的只讀屬性？

**Comment by aweiu** [comment]
@chenpion 就是[$attrs](https://cn.vuejs.org/v2/api/#vm-attrs)和[$listeners](https://cn.vuejs.org/v2/api/#vm-listeners)这两个属性是Vue实例的只读属性，注意检查下代码，不要直接修改它们
