### ISSUE TITLE
watch在特定场景下会有问题

### ISSUE THREAD

**Issue by changming1987117** [aweiu/element-ui-verify#16]
大神好：
实际场景如下：
变量A的校验依赖于B
A在B=0的时候可以为空，在B=1的时候不能为空
问题出在以下这段代码，对应版本1.1.4
compnent.js第39行
 if (fieldValue === '') {
            return [{
                    validator: (rule, val, callback) => {
                        if (this.canBeEmpty !== undefined || this.minLength <= 0)
                            callback();
                        else
                            callback(Error(this.emptyMessage || errorMessage.get('empty')));
                    }
                }];
        }

当A为空的时候，将B值修改为1，正好命中这段代码逻辑，导致不能调用A的自定义校验方法
能否改成，如果有watch的时候始终保持调用校验

**Comment by aweiu** [comment]
这个问题其实考虑过。
比如该插件的原型[vue-verify-pop](https://github.com/aweiu/vue-verify-pop#canbenull)对该问题的处理方式

针对该类需求，如果简单地用`如果有watch的时候始终保持调用校验`，还不如采用上面始终会执行的方式，统一某个特性才不会让调用者困惑，以免引出新的问题。

然后本插件之所以没有再次实现这个特性，主要是考虑到目前来看，
**输入框可以为空，然而为空时还要调用自定义校验**的需求要远小于**输入框可以为空，为空不校验，不为空才校验**，以避免调用者每次都要在自定义校验方法里判断值是否为空。

废话说完了，至于该种情况该如何处理，有两种相对合理的方式：
1. 直接用Element的原生校验
2. 参考[常见问题](https://github.com/aweiu/element-ui-verify#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)中的切换校验类型。
```
<!--表单A-->
<el-form-item prop="A" verify :can-be-empty="model.B === '1' ? undefined : true></el-form-item>
```

**Comment by changming1987117** [comment]
哦哦，好的，非常感谢您的回复
