### ISSUE TITLE
打包后js体积暴增

### ISSUE THREAD

**Issue by luyunyu** [aweiu/element-ui-verify#18]
在import element-ui-verify 之前，我的app.js大小为2430kb， 引入之后暴增到4045kb，这个源代码体积并不大，为什么会差距这么大呢，我使用的element-ui版本为2.4.6， vue版本为2.5.16

**Comment by aweiu** [comment]
上传一份demo过来？

**Comment by luyunyu** [comment]
抱歉，我是新手，还不太熟github，您这么回复的话，应该在你那没有出现这样的情况，是否可以告知一下你使用的element-ui和vue的版本，我试一下你推荐的版本
