### ISSUE TITLE
在IE11浏览器，报错：Expected ';'

### ISSUE THREAD

**Issue by zeronyist** [aweiu/element-ui-verify#20]
测试代码如下：
[e-v.zip](https://github.com/aweiu/element-ui-verify/files/2335465/e-v.zip)
babel设置如下：
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": ["transform-vue-jsx", "transform-runtime"],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["transform-vue-jsx", "transform-es2015-modules-commonjs", "dynamic-import-node"]
    }
  }
}
在IE11下报错：
![error](https://user-images.githubusercontent.com/33652448/44842430-611acf00-ac78-11e8-9c2f-2563fd466701.png)

**Comment by aweiu** [comment]
好的。不过暂时没时间维护，你先尝试自己解决下吧。如果确定是插件本身引起的兼容问题，欢迎提交pr

**Comment by zeronyist** [comment]
是我使用的问题。非系统BUG，关闭bug

**Comment by EchoWht** [comment]
@zeronyist 你好！请教一下你是如何解决的此问题？
