### ISSUE TITLE
支持一些新的手机号段，比如199等

### ISSUE THREAD

**Issue by dragoncz** [aweiu/element-ui-verify#24]
手机号码新增了 199（电信），198（移动），166（联通）三个号段，具体可参考[这里](http://tech.sina.com.cn/mobile/n/n/2017-11-20/doc-ifynwnty5537039.shtml)

需要更新下匹配的正则表达式，以支持新号段

**Comment by dragoncz** [comment]
@aweiu 神速的修复👍

不过还需要补充 191 以及 167 号段的支持 

- [知乎](https://zhuanlan.zhihu.com/p/40878967)
- [维基百科](https://zh.wikipedia.org/wiki/中国内地移动终端通讯号段)

不好意思，我之前提的时候漏掉了

**Comment by aweiu** [comment]
@dragoncz 要不你去[这里](https://github.com/VincentSit/ChinaMobilePhoneNumberRegex)也提个issue？

**Comment by dragoncz** [comment]
> @dragoncz 要不你去[这里](https://github.com/VincentSit/ChinaMobilePhoneNumberRegex)也提个issue？

事实上，我去那里看过了，作者自己提了这么个 [issue...](https://github.com/VincentSit/ChinaMobilePhoneNumberRegex/issues/9#issue-350791911)

**Comment by aweiu** [comment]
要不。。。你给他提个pr吧！😂

**Comment by dragoncz** [comment]
@aweiu 
我去研究下哈哈。

另外一个可能的 quick fix 方案：

`/^(?=\d{11}$)^1(?:3\d|4[57]|5[^4\D]|66|7[^249\D]|8\d|9[89])\d{8}$/`
改成
`/^(?=\d{11}$)^1(?:3\d|4[57]|5[^4\D]|6[67]|7[^249\D]|8\d|9[189])\d{8}$/`

不知可行不

**Comment by aweiu** [comment]
[没毛病！](https://regexper.com/#%5E%28%3F%3D%5Cd%7B11%7D%24%29%5E1%28%3F%3A3%5Cd%7C4%5B57%5D%7C5%5B%5E4%5CD%5D%7C6%5B67%5D%7C7%5B%5E249%5CD%5D%7C8%5Cd%7C9%5B189%5D%29%5Cd%7B8%7D%24)不过有些后悔让插件自带手机号校验了。。。

**Comment by dragoncz** [comment]
@aweiu 自己挖的坑含泪也要填完。。
