### ISSUE TITLE
el-select 和 el-input 校验形式不同

### ISSUE THREAD

**Issue by Sinosaurus** [aweiu/element-ui-verify#25]
##### 需求
> 后台数据回显不触发校验，当编辑时再触发校验

```设置了 clear 形式
Vue.use(elementUIVerify, {
  fieldChange: 'clear'
})
```
这样回显时不触发校验，很ok，但是在编辑时，`el-input`可以正常触发校验，输入框变为绿色，但是`el-select`却无法变色，感觉就是没进行校验（切换不同值）。这个一直使用element的痛点，不知这里改如何处理比较好
![element-ui-validate](https://user-images.githubusercontent.com/31885010/50040234-a1148f00-007a-11e9-9048-60e0759e3e07.gif)

> 如图片上所示，select已经不会发生任何变化了

**Comment by aweiu** [comment]
@Sinosaurus 我这边复现不了你这个问题

**Comment by Sinosaurus** [comment]
@aweiu 
#### 版本
+ element-ui  **2.4.11**
+ vue **2.5.17**

```使用element-ui自带的校验
rules: {
        name: [
          { required: true, message: "请输入活动名称", trigger: "blur" },
          { min: 3, max: 5, message: "长度在 3 到 5 个字符", trigger: "blur" }
        ],
        region: [
          { required: true, message: "请选择活动区域", trigger: "change" }
        ],
        type: [
          {
            type: "array",
            required: true,
            message: "请至少选择一个活动性质",
            trigger: "change"
          }
        ],
        resource: [
          { required: true, message: "请选择活动资源", trigger: "change" }
        ],
        desc: [{ required: true, message: "请填写活动形式", trigger: "blur" }]
      },
```

![element](https://user-images.githubusercontent.com/31885010/50054964-6b0f0200-0183-11e9-96d0-bbabd8d84831.gif)
>原生使用时，数据回显时，会触发`el-select`的校验， 而`el-input`的校验却没有触发

> ------------------- 使用 element-ui-verify --------------------

```使用默认配置
import ElementUi from 'element-ui'
import ElementUiVerify from 'element-ui-verify'
import 'element-ui/lib/theme-chalk/index.css'
Vue.use(ElementUi)
Vue.use(ElementUiVerify)
```

![element-verify](https://user-images.githubusercontent.com/31885010/50055071-b7a70d00-0184-11e9-9234-651b649610b9.gif)
> 数据回显时，`el-input` 和 `el-select`都会进行校验 ，颜色都变为绿色

>-----------------添加fieldChange: 'clear'-----------

```
import ElementUi from 'element-ui'
import ElementUiVerify from 'element-ui-verify'
import 'element-ui/lib/theme-chalk/index.css'
Vue.use(ElementUi)
Vue.use(ElementUiVerify, {
  fieldChange: 'clear'
})
```

![element-verify2](https://user-images.githubusercontent.com/31885010/50055119-516eba00-0185-11e9-8ffd-8002979f5354.gif)

> 可以看出设置了 `clear`之后，`el-select`再进行校验时，也不会再进行触发了。 不知是否要进行自定义校验吗？

+ 附上源码一份**不支持上传.vue**修改为了`txt`

[verify.txt](https://github.com/aweiu/element-ui-verify/files/2683648/verify.txt)

**Comment by aweiu** [comment]
为你描述问题的能力和方法点赞，你这个问题明天有空的话再测下

**Comment by aweiu** [comment]
为你描述问题的能力和方法点赞，你这个问题明天有空的话再测下

**Comment by Sinosaurus** [comment]
@aweiu 好呢，感谢啦，这个帮我解决好多之前element上不好处理的问题

**Comment by aweiu** [comment]
@Sinosaurus 
这个问题有点小复杂
根本原因在于 Element 的 Select 组件在选择的时候只会触发 `fieldChange` 事件，所以一旦你把本插件的 `fieldChange` 设置成了 `clear` ,会始终执行清除校验结果，不会有机会接收到 `blur` 事件来重新触发校验

我这边倒是可以再通过 Mixin 的方式去修改 Select 组件的行为来满足这类场景，不过感觉太不清真了
而且它的这种行为倒也不能算是 bug ，只能说和其他 `Input` 类组件的事件机制不统一，所以如果直接给 Element 提 issue 估计没指望

在说其他办法之前不知道你有没有尝试过单独给 Select 设置  `fieldChange` 为 `verify`？

**Comment by Sinosaurus** [comment]
@aweiu
 非常感谢测试许久，我也想单独将`select`和`input`分离开来，但是我这的表单太大，有四五十个，他俩差不多五五开，因而那样设置就有些恐怖了。不过你说这个方式我可以试试（之前没有试过）

 我跟产品交流许久，其实他们的意思反而是，希望回显数据后就进行校验，这样让用户更加清晰开到那些是对，那些是错。若是这样，我这个问题也就不是问题了。但是我本着发现问题就深究的准则。我还是想弄清楚原因。

我晚点照你这个方式再试试。感谢，若是还有其他问题，还望不吝赐教

**Comment by aweiu** [comment]
嗯，深究是个好习惯。
如果真的要追求一致的交互，你这个需求如果单单去改 Select 也可能会有问题，就是其他输入区域没有红而 Select 红了。不过解决办法还是有的，欢迎测试讨论
反倒是你们产品的需求好实现了

**Comment by Sinosaurus** [comment]
你好，这个问题可以先关闭了。另外我有几个实际问题，希望能解惑一下，我看这个文档已经好几遍了，没有很好地思路

> `can-be-empty`   **verify,canBeEmpty,space,number,int等无须接收值的选项一旦设置了，可以通过赋值为undefined来取消**
这个可以设置`Boolean`类型吗？这样我好控制，我看了源码，只能是`String` （需求是，当某一个值填了，这个便是必填项，否则可不填）

> 前台后台校验结果可否结合一起， 因为有些错误信息是后台返回的，目前我只能弹窗，是否可以将这个结合在一起呢

**Comment by aweiu** [comment]
> 这个可以设置Boolean类型吗

不可以

> 需求是，当某一个值填了，这个便是必填项，否则可不填

解决方案：
```
:can-be-empty = "someVal === '' ? '' : undefined"
```


> 前台后台校验结果可否结合一起

可以，解决方案：
由于 `error-message` 不是响应式的，所以你需要在后端返回校验结果的时候手动去重新触发相应输入字段的校验来实现更新错误提示内容。或者可以使用 [watch](https://github.com/aweiu/element-ui-verify#watch) 来监听 `error-message` 绑定值的变化来触发自动校验
建议使用第一个方案，封装一个 `el-form` wraper，用它来自动化地完成后端校验结果的获取和前端校验的重新触发。
当然了，也不排除你可能需要的只是异步校验，那直接用[自定义校验方法](https://github.com/aweiu/element-ui-verify#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%A1%E9%AA%8C%E6%96%B9%E6%B3%95)来做吧

**Comment by Sinosaurus** [comment]
@aweiu 好呢，非常感谢
