### ISSUE TITLE
能否提供一份编译完的js

### ISSUE THREAD

**Issue by foryoufeng** [aweiu/element-ui-verify#26]
就是直接可以在页面应用的js,不需要进行编译的，如

- <script src="/vendor/js/vue.js"></script>
- <script src="/vendor/js/axios.js"></script>
- <script src="/vendor/js/element-2.4.js"></script>
- <script src="/vendor/js/你的验证的js"></script>

**Comment by aweiu** [comment]
再看看吧，貌似需要这个的还不是很多。。。

**Comment by foryoufeng** [comment]
我是做后端的，一般都不会用.vue来做前后端分离，自己写点小项目，所以需要编译好的js,上面那几个我都是这样引用的，而且编译好的js新手好上手~~

**Comment by Cendeal** [comment]
ie浏览器能兼容吗？
