### ISSUE TITLE
应该增加maxLength的功能 用的也比较多 

### ISSUE THREAD

**Issue by JamesRouwanzi** [aweiu/element-ui-verify#28]
应该增加maxLength的功能 用的也比较多，我在本机上增加了 建议作者加上 最大长度判断。

**Comment by JamesRouwanzi** [comment]
maxLength: '输入内容不能大于{maxLength}位',

**Comment by aweiu** [comment]
事实上，我是刻意没有加这个的 
如你所说，这确实是很常见的场景，但因为`maxlength` 是 `input` 标签原生就支持的最大字符数限制指令：
```
<el-input maxlength="3"></el-input>
```
这样直接就无法输入超过「3」个字符，大多数场景下这样就 ok 了，所以我加了这个规则也不会触发
除非真的要刻意不用原生字符限制，想用校验错误来提示用户，不过这样的话这个规则实际上就不再是一个「常用」场景了
所以就没有加入到插件的默认规则中
