### ISSUE TITLE
如何校验 日期，数组等数据类型？

### ISSUE THREAD

**Issue by kele59** [aweiu/element-ui-verify#29]
日期和数组在表单中还挺常见的，只能通过手动写自定义校验才行吗？

默认支持的校验规则没有 date 和 array 类型

**Comment by aweiu** [comment]
你这里只提了类型，没有提校验逻辑。比如，数组是校验它的长度吗？date 是校验范围？而且 date 可能还会涉及到类型转换

因此插件一般不会自带这些高级类型的校验，太依赖业务了。建议你使用 [自定义校验规则](https://github.com/aweiu/element-ui-verify#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%A1%E9%AA%8C%E8%A7%84%E5%88%99)来扩展。或者在全局共享一些通用的校验方法
