### ISSUE TITLE
插件的默认校验不通过提示模版

### ISSUE THREAD

**Issue by liaoyinglong** [aweiu/element-ui-verify#3]
```
{
   empty: '请补充该项内容',
    ...
}
```
看了一下好像并没有提供接口让我修改默认校验不通过提示模版。
通常情况下是不需要修改，但是现在有一个问题的就是，空校验是优先级最高的，但是这个提示并不符合我们的需求，这种情况下我应该如何修改？fork一份源码来改吗？亦或者提供一下接口？
谢谢。

**Comment by aweiu** [comment]
可以修改的，可能是之前文档描述的不清楚
https://github.com/aweiu/element-ui-verify/blob/master/README.md#配置

**Comment by liaoyinglong** [comment]
好的，谢谢，应该是我没看仔细
另外还有一个问题。关于打包后的代码问题
```bash
$ npm i element-ui-verify --save
```
下载下来的代码是
![2018-01-03_17h22_43](https://user-images.githubusercontent.com/23382699/34515198-e8f4a7f4-f0ab-11e7-8d41-6b0b57dc2b7c.png)

打包出来的代码会将 element-ui和vue重复打包一份 ？
原因还在查看

**Comment by aweiu** [comment]
应该和npm版本和package.json配置有关系，这个确实需要研究一下

**Comment by aweiu** [comment]
应该和npm版本和package.json配置有关系，这个确实需要研究一下

**Comment by aweiu** [comment]
@liaoyinglong 我更新了，重复打包的问题应该解决了
顺便，你再告诉我一下你的npm,vue,element-ui分别是什么版本

**Comment by liaoyinglong** [comment]
@aweiu 
npm  5.5.1
"vue": "2.3.4"
"element-ui": "1.4.12"
明天我更新一下试试看

**Comment by aweiu** [comment]
@liaoyinglong 你的vue和element-ui的版本都太低了。。
我刚更新的那个版本肯定不行 不过明天我可以用你这个环境再测试一下是否可以兼容

**Comment by liaoyinglong** [comment]
![tim 20180104093441](https://user-images.githubusercontent.com/23382699/34546959-8920eb94-f132-11e7-9498-4723f20a2de0.png)
不行。。更尴尬的事情发生了 ，我猜测是tsc的问题？

**Comment by liaoyinglong** [comment]
```
 ElFormItemComponent.mixin(Component);
```
初步判定是这段代码在我的环境出现问题，尝试以其他方式混入

**Comment by aweiu** [comment]
"vue": "2.3.4"
"element-ui": "1.4.12"
我刚测了 没有出现你上面的错误

**Comment by liaoyinglong** [comment]
原因找到了。。是因为我有全局的mixins注册，例如这种
```javascript
import elementUIVerify from 'element-ui-verify';
Vue.use(elementUIVerify);
// 引入全局mixins
import * as mixins from './mixins';
Object.keys(mixins).forEach(key => {
   Vue.mixin(mixins[key]);
});
```
我这边有一些方法要注册成全局的，然后好像冲突了
@aweiu 有空再试一下？

**Comment by aweiu** [comment]
你的这种冲突只能自己在项目中排查了
我刚刚提交了更新，更新了vue和element-ui的最低依赖版本

**Comment by liaoyinglong** [comment]
好的，我想一下其他办法，thank you very much

**Comment by liaoyinglong** [comment]
我解决了
@aweiu 
稍后我提个pr你看一下
