### ISSUE TITLE
与element2.9.1版本冲突了么

### ISSUE THREAD

**Issue by SCAUZSJ** [aweiu/element-ui-verify#33]
引入后报错./node_modules/_element-ui@2.9.1@element-ui/lib/element-ui.common.js
Module not found: Error: Can't resolve 'element-ui/lib/cascader-panel' in 'D:\document\vue\XXX\node_modules\_element-ui@2.9.1@element-ui\lib'

**Comment by aweiu** [comment]
已测试没有冲突，而且这个错误信息来看也不是本插件引发的。你再检查下吧

**Comment by SCAUZSJ** [comment]
好的。原因是我一开始用cnpm去装，没报错，结果引入就报上面的错误。试了下npm装后就没问题了！谢谢，插件很强大
