### ISSUE TITLE
默认校验规则 number异常

### ISSUE THREAD

**Issue by SCAUZSJ** [aweiu/element-ui-verify#34]
代码：
<el-form-item prop="a" class="text-right" verify number >
     <el-input v-model="data.a" placeholder="0" ></el-input>
</el-form-item>
 不管输入什么都显示不是数字。。请问是什么问题
![image](https://user-images.githubusercontent.com/22726846/58932610-fbbfb580-8796-11e9-94fa-b39d7cbdcd83.png)

**Comment by SCAUZSJ** [comment]
![image](https://user-images.githubusercontent.com/22726846/58932663-27db3680-8797-11e9-9b5e-45fa618d14b0.png)

**Comment by aweiu** [comment]
这个是强 number 类型校验，输入框接收到的值实际上是字符串，所以需要你配合 [v-model.number](https://cn.vuejs.org/v2/guide/forms.html#number) 使用。
