### ISSUE TITLE
v1.2.0 typings 报错

### ISSUE THREAD

**Issue by Allenice** [aweiu/element-ui-verify#38]
![image](https://user-images.githubusercontent.com/2650994/63071977-072c1b80-bf54-11e9-9614-ec6c50087e31.png)
type.d.ts 没有了

**Comment by aweiu** [comment]
@Allenice 已修复

**Comment by aweiu** [comment]
好像还有问题，处理中...

**Comment by aweiu** [comment]
应该可以了，可以测下？
