### ISSUE TITLE
关于multiple 自动触发非空校验

### ISSUE THREAD

**Issue by wangyangyangyang** [aweiu/element-ui-verify#39]
多选框会自动触发非空校验，请问是不支持Checkbox 么？

**Comment by aweiu** [comment]
理论上是支持所有组件的，因为是它校验的只是 `form-item` 绑定的数据。
放一个用例上来吧

**Comment by wangyangyangyang** [comment]
> 多选框会自动触发非空校验，请问是不支持Checkbox 么？



> 理论上是支持所有组件的，因为是它校验的只是 `form-item` 绑定的数据。
> 放一个用例上来吧
嗯嗯仔细检查了下，绑定的应该是个数组，我给改成了字符串了
