### ISSUE TITLE
alias设计不错，人性化，傻瓜化。。。

### ISSUE THREAD

**Issue by wujianqi** [aweiu/element-ui-verify#43]
async-validator 确实太繁琐了，无奈也撸了一个，可惜不太兼容。顺便借鉴了作者“alias”的设计，冒犯了， 不好意思。https://github.com/wujianqi/qi-validator

**Comment by aweiu** [comment]
能给其他开源项目带来灵感也是开源的目的之一，当然是一件值得高兴的事情，共勉~
