### ISSUE TITLE
请问是否可以根据后台返回的错误信息主动触发某个field的error？

### ISSUE THREAD

**Issue by zengcul** [aweiu/element-ui-verify#6]
<el-row>
      <el-col :span="6">
        <el-input v-model="mainForm.name" placeholder="名称"></el-input>
      </el-col>
      <el-button type="primary" @click="createData">提交</el-button>
  </el-form>

后端返回 response =  {'name':''名称已存在'}  

请问 前端有没有方法去触发 <el-input v-model="mainForm.name" placeholder="名称"></el-input>报错

**Comment by aweiu** [comment]
[自定义校验方法](https://github.com/aweiu/element-ui-verify#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%A1%E9%AA%8C%E6%96%B9%E6%B3%95)可以实现这种异步校验

不过你这个需求个人觉得应该放在网络请求层来做，response拦截器里判断该类错误的统一标志来校验更恰当。因为即使在输入的那一刻，异步校验的结果是正确的，等其它表单输入完后再提交至后端时依然有可能`name已存在`，故这个校验不推荐放在表单校验层，因为结果不可靠

这个要求前后端协商一个统一的response结构，如：
```
{msg: '提交成功', data: xxx}
{errMsg: '该用户已存在', data: xxx}
```

**Comment by zengcul** [comment]
我后端返回的格式是已经统一的
{msg: 提交失败,data: {name:已存在,age:年纪过大}，类似这样，每个错误都有字段名和错误信息，想做成跟在提交表单控件相应位置下报错，更清晰点。
在拦截器里只能用message box ，

**Comment by aweiu** [comment]
@zengcul 
如果业务中大量存在这种异步校验需求可以自己[拓展一个异步校验的规则](https://github.com/aweiu/element-ui-verify#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%A1%E9%AA%8C%E8%A7%84%E5%88%99)

比如，规则名称可以为`v-api`
```
<el-form-item label="名称" prop="name" verify v-api="YourVerifyApi" field-change="clear">
  <el-input v-model="model.name"></el-input>
</el-form-item>
```
具体实现再参考上面的文档结合根据你的业务来做吧

如果这类需求不是很多，依然可以使用[自定义校验方法](https://github.com/aweiu/element-ui-verify#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%A1%E9%AA%8C%E6%96%B9%E6%B3%95)来做
