### ISSUE TITLE
特定条件下数字校验失败（好像是bug）

### ISSUE THREAD

**Issue by zengcul** [aweiu/element-ui-verify#8]
下面是我的使用方式，当输入数字开头时校验失败，比如“2eee”
```
<el-form-item label="库存总量" prop="left_amount" verify int >
      <el-input v-model.number="model.left_amount"></el-input>
 </el-form-item>
```
vue版本：2.5.9
elelmentui版本：2.0.11

**Comment by aweiu** [comment]
没懂，把你的`form-item`或校验规则发来看看吧
然后这个"2eee"是指输入的内容么

**Comment by zengcul** [comment]
不好意思  刚没把那段代码块引用下     
```
<el-form-item label="库存总量" prop="left_amount" verify int >
      <el-input v-model.number="model.left_amount"></el-input>
 </el-form-item>
```
当输入数字开头后面跟上字母，数字验证失效，我的vue版本比您要求的高了点 不知道是不是这个原因，
![image](https://user-images.githubusercontent.com/12690147/38067659-2bd11d24-3340-11e8-8dad-6c42c6db2b75.png)这么输入时不会提示错误，但是实际上model里绑定的值已经把字母过滤掉了 ，validate是成功的，仅仅是输入时不会提示错误

**Comment by aweiu** [comment]
事实上，这个其实是[v-model.number](https://cn.vuejs.org/v2/guide/forms.html#number)的特性

当你输入数字开头的字符时，`v-model.number`会取开头数字作为`this.data.model.left_amount`的值，也就是说实际上“2eee”只是个显示值，实际值是其实是数字2。如果你输入"2.1eee"，同理插件会提示你”请输入整数“。更多细节可参考`vue.toNumber`[源码](https://github.com/vuejs/vue/blob/d982e344b39391fe91b6dd91d51b2f0310a45e77/src/shared/util.js#L89)

题外话，数字校验这里之前考虑过完全取输入值做强校验，这样可以使"显示值"与"实际值"保持一致，不过坏处是会对使用了`v-model.number`指令的人造成困惑

**Comment by zengcul** [comment]
多谢作者耐心解释，加个type="number" 会不会好点 ，显示值输入的时候就会把非法字母给退回，毕竟那个现象是个bug
```
<el-form-item label="库存总量" prop="left_amount" verify int :gt="0">
      <el-input v-model.number="mainForm.left_amount" type="number"></el-input>
</el-form-item>
```

**Comment by aweiu** [comment]
其实你可以考虑在输入框附近做一个label来实时显示输入的实际值
